name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: kivy/buildozer-action@v0.4
      with:
        buildozer_version: stable
        # Этот параметр сам скачает и настроит SDK/NDK внутри контейнера
        android_sdk: true
        android_ndk: true
      env:
        # Автоматическое принятие лицензии
        ANDROID_SDK_HOME: /usr/local/lib/android/sdk
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: My-Android-App
        path: bin/*.apk
        
